openapi: 3.0.0
info:
  title: Account API
  version: 1.0.0
servers:
  - url: http://localhost:8080/

paths:
  /api/v1/accounts/{Id}:
    get:
      summary: Get account details
      operationId: getAccount
      tags:
        - Accounts
      parameters:
        - name: Id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found

  /api/v1/accounts:
    post:
      summary: Create a new account
      operationId: createAccount
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Account created
        '400':
          description: Invalid input

  /api/v1/transactions:
    post:
      summary: Process a transaction
      operationId: processTransaction
      tags:
       - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Transaction processed
        '400':
          description: Invalid input



components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        typeOfAccount:
          type: string
        balance:
            $ref: '#/components/schemas/Balance'

    AccountRequest:
      type: object
      properties:
        typeOfAccount:
          type: string
        balance:
            $ref: '#/components/schemas/Balance'

    Balance:
      type: object
      properties:
        amount:
          type: string
          format: decimal

    TransactionRequest:
      type: object
      properties:
        transactionType:
          $ref: '#/components/schemas/TransactionType'
        accountSource:
          type: integer
          format: int64
        accountDestination:
          type: integer
          format: int64
        amount:
          $ref: '#/components/schemas/Balance'

    TransactionType:
      type: string
      enum:
        - DEPOSIT
        - WITHDRAW
        - TRANSFER
