spring:
  application:
    name: account

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
    mapping-resources:
      - account-system-orm.xml

server:
  servlet:
    context-path: /api/v1
  port: 8080
